{% set name = "httplib2shim" %}
{% set version = "0.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c61daebd93ed7930df9ded4dbf47f87d35a8f29363d6e399fbf9fec930f8d17

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - certifi
    - httplib2
    - python >={{ python_min }}
    - six
    - urllib3

test:
  imports:
    - httplib2shim
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/GoogleCloudPlatform/httplib2shim
  summary: A wrapper over urllib3 that matches httplib2's interface
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
